//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chothuexe1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHOADON
    {
        public int MaHD { get; set; }
        public int MaXe { get; set; }
        public Nullable<int> ThoiGianThue { get; set; }
        public string TrangThaiThue { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual XETHUE XETHUE { get; set; }
    }
}
