//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chothuexe1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        public int MaDG { get; set; }
        public Nullable<int> MaTK { get; set; }
        public Nullable<int> MaXe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> DiemSo { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual XETHUE XETHUE { get; set; }
    }
}
