//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chothuexe1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
            this.DIACHINHANXEs = new HashSet<DIACHINHANXE>();
        }
    
        public int MaHD { get; set; }
        public Nullable<int> MaTK { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<bool> TrangThaiNhanXe { get; set; }
        public Nullable<System.DateTime> NgayTaoHD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIACHINHANXE> DIACHINHANXEs { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
